### ISSUE TITLE
toString Это же метод, почему без скобок?

### ISSUE THREAD

**Issue by DanilParshukov** [AbdalimovArtur/scala-dialogflow#1]
https://github.com/AbdalimovArtur/scala-dialogflow-v2-samples/blob/e2882c51de8bd41b657cc0f131abab316d1b5ffa/src/main/scala/BootApp.scala#L7

**Comment by arturka** [comment]
Да, это метод. В Scala, если метод имеет 0 аргументов, то можно не ставить скобки, НО если твой метод меняет внутреннее состояние объекта и у него 0 аргументов, то скобки ставить нужно. Спасибо за коммент
